language: node_js
sudo: false
node_js:
  - 0.10
cache:
  directories:
    - node_modules
    - bower_components
before_install:
 # Log HTTP requests
  - npm config set loglevel http
  - npm install -g npm@2.5
  - npm install -g gulp
  - npm install -g bower
script:
  - gulp test
env:

